name: petal_vision
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  tflite_flutter: ^0.11.0
  image: ^3.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0  # ✅ No conflict with image 3.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/petalvision.png"

flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt
    - assets/flower_recognition_model.tflite
    - assets/images/daisy.png
    - assets/images/dandelion.png
    - assets/images/lavender.png
    - assets/images/lilly.png
    - assets/images/lotus.png
    - assets/images/orchid.png
    - assets/images/rose.png
    - assets/images/sunflower.png
    - assets/images/tulip.png
